# Site settings
title: Simon Janin's Blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Simon Janin writes articles on various books, computer and technology, self-improvement and social issues.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonjanin.ch" # the base hostname & protocol for your site
twitter_username: 
github_username:  simonjanin

# Build settings
markdown: kramdown
